config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  devise_for :teachers, controllers: {
    registrations: 'teachers/registrations',
    confirmations: 'teachers/confirmations'
  }
  devise_for :students, controllers: {
    registrations: 'students/registrations',
  }
  mount StripeEvent::Engine, at: '/stripe/webhook'
  root to: 'home#index'
  namespace :students do
    resources :lessons, only: [:index] do
      resource :reservation, only: [:create], module: :lessons
      resource :feedback, only: [:show], module: :lessons
    end
    resources :reservations, only: [:index]
    resources :payments, only: [:new, :create] do
      collection do
        get :success
        get :cancel
      end
    end
  end
  namespace :admins do
    resources :teachers, only: [:index, :destroy] do
      member do
        post :become
      end
    end
    resources :reservations, only: [:index] do
      collection do
        get :by_teacher
        get :by_language
      end
    end
  end
  namespace :teachers do
    resources :lessons, only: [:index, :new, :create] do
      collection do
        get :bulk_search
        get :bulk_new
        post :bulk_create
        post :recreate_zoom_user
      end
      resource :feedback, only: [:new, :edit, :create], module: :lessons
      resource :report, only: [:new, :edit, :create], module: :lessons
    end
    resources :students, only: [:show]
  end
  resources :teachers, only: [:show]
  Rails.env.development? && mount(LetterOpenerWeb::Engine, at: '/letter_opener')
end

app/models/reservation.rb
class Reservation < ApplicationRecord
  belongs_to :student
  belongs_to :lesson

  with_options presence: true do
    validates :lesson, uniqueness: true
    validates :tickets_before, :tickets_after
    validates :start_url, :join_url, {
      format: { with: %r{https?://.+} },
      uniqueness: true
    }
  end
  validate :lesson_start_time_expect_to_be_after_now

  def lesson_start_time_expect_to_be_after_now
    errors.add(:lesson, '開始時刻を過ぎているレッスンは予約できません') if lesson.started?
  end

  scope :load_lesson_not_started, lambda {
    eager_load(:lesson)
      .where('lessons.start_time > ?', Time.now.ago(Lesson::MEETING_DURATION_MINUTES.minute))
  }
  scope :sorted, -> { order('lessons.start_time asc') }

  def reserve
    return false unless lesson.valid?

    return false unless spend_ticket

    assign_zoom_meeting
    return false unless valid?

    ActiveRecord::Base.transaction do
      student.save!
      save!
    rescue ActiveRecord::RecordInvalid
      return false
    end
    reserved_mail
    true
  end

  def spend_ticket
    self.tickets_before = student.tickets
    student.tickets -= 1
    self.tickets_after = student.tickets
    # 本当はstudent.valid?とDRYにしたいが、ticketsのバリデーションだけ判定するのが難しい
    student.tickets >= 0
  end

  def create_zoom_meeting
    Zoom.new.meeting_create(
      user_id: lesson.teacher.zoom_user_id,
      start_time: lesson.start_time.in_time_zone('UTC'),
      duration: Lesson::MEETING_DURATION_MINUTES
    )
  end

  def assign_zoom_meeting
    meeting = create_zoom_meeting
    self.start_url = meeting['start_url']
    self.join_url = meeting['join_url']
  end

  def reserved_mail
    TeacherMailer.reserve(self).deliver_later
    StudentMailer.reserve(self).deliver_later
  end
end

app/controllers/admins/reservations_controller.rb
class Admins::ReservationsController < ApplicationController
  before_action :authenticate_admin!
  before_action :query_dates

  def index
    @lessons_counts = Lesson.count_by_date_and_time(@start_date, @end_date)
    @reservations_counts = Lesson.reserved_count_by_date_and_time(@start_date, @end_date)
  end

  def by_teacher
    @teachers = Teacher.all
    case params[:span]
    when 'monthly'
      @lessons_counts = Lesson.count_by_month_and_teacher
      @reservations_counts = Lesson.reserved_count_by_month_and_teacher
      render 'by_teacher_and_month'
    when 'daily'
      @lessons_counts = Lesson.count_by_date_and_teacher(@start_date, @end_date)
      @reservations_counts = Lesson.reserved_count_by_date_and_teacher(@start_date, @end_date)
      render 'by_teacher_and_date'
    end
  end

  def by_language
    @languages = Language.all
    case params[:span]
    when 'monthly'
      @lessons_counts = Lesson.count_by_month_and_language
      @reservations_counts = Lesson.reserved_count_by_month_and_language
      render 'by_language_and_month'
    when 'daily'
      @lessons_counts = Lesson.count_by_date_and_language(@start_date, @end_date)
      @reservations_counts = Lesson.reserved_count_by_date_and_language(@start_date, @end_date)
      render 'by_language_and_date'
    end
  end

  private

  def query_params
    params.fetch(:query, { start_date: Date.today, end_date: Date.today }).permit(:start_date, :end_date)
  end

  def query_dates
    @start_date = Date.parse(query_params[:start_date]) rescue 1.week.ago(Date.today)
    @end_date = Date.parse(query_params[:end_date]) rescue Date.today
  end
end

app/controllers/students/lessons/reservations_controller.rb
class Students::Lessons::ReservationsController < ApplicationController
  before_action :authenticate_student!

  def create
    reservation = current_student.reservations.build(lesson_id: params[:lesson_id])
    if reservation.reserve
      redirect_to students_lessons_path, method: :get, notice: '予約が完了しました'
    else
      redirect_to students_lessons_path,
                  method: :get,
                  alert: (current_student.errors.full_messages + reservation.errors.full_messages + reservation.lesson.errors.full_messages).join(', ')
    end
  rescue Zoom::Error => e
    redirect_to students_lessons_path, method: :get, danger: "Zoom予約のエラーにより、予約が失敗しました。管理者にお問い合わせください: #{e.message}"
  end
end

app/controllers/students/reservations_controller.rb
class Students::ReservationsController < ApplicationController
  before_action :authenticate_student!

  def index
    @reservations = current_student.reservations.includes(lesson: :teacher).includes(lesson: :feedback).sorted
  end
end

app/helpers/reservation_helper.rb
module ReservationHelper
  def style_class_by_reserved_rate(rate)
    if rate.blank?
      nil
    elsif rate > 85
      'reserved-rate-high'
    elsif rate > 50
      'reserved-rate-middle'
    else
      'reserved-rate-low'
    end
  end

  def reserved_rate(reservations_count, lessons_count)
    if lessons_count.blank?
      nil
    else
      (reservations_count || 0) * 100 / lessons_count
    end
  end

  def create_daily_query_params(month)
    {
      'span' => 'daily',
      'query[start_date]' => month.to_s(:date_query),
      'query[end_date]' => month.end_of_month.to_s(:date_query)
    }
  end
end

app/views/admins/reservations/_links.html.haml
= link_to_unless_current '時間別', admins_reservations_path
= link_to_unless_current '講師別', by_teacher_admins_reservations_path({span: 'monthly'})
= link_to_unless_current '言語別', by_language_admins_reservations_path({span: 'monthly'})

app/views/admins/reservations/_td_reserved_rate.html.haml
- if lessons_count.nil?
  %td -
- else
  %td{class: "#{style_class_by_reserved_rate(reserved_rate(reservations_count, lessons_count))}"}
    #{reservations_count || 0} / #{lessons_count}
    %br
    (#{reserved_rate(reservations_count, lessons_count)}%)

app/views/admins/reservations/by_language_and_date.html.haml
%h2
  言語別予約率
= render 'links'
%table.table
  %thead
    %tr
      %th 日付
      - @languages.each do |language|
        %th
          = language.name
  %tbody
    - (@start_date..@end_date).each do |date|
      %tr
        %th
          = date.to_s(:date_jp_weekday)
        - @languages.each do |language|
          = render 'td_reserved_rate', reservations_count: @reservations_counts[[date, language.id]], lessons_count: @lessons_counts[[date, language.id]]

app/views/admins/reservations/by_language_and_month.html.haml
%h2
  言語別予約率
= render 'links'
%table.table
  %thead
    %tr
      %th 日付
      - @languages.each do |language|
        %th
          = language.name
  %tbody
    - month_enum(*Lesson.date_range).each do |month|
      %tr
        %th
          = link_to month.to_s(:month_jp), by_language_admins_reservations_path(create_daily_query_params(month))
        - @languages.each do |language|
          = render 'td_reserved_rate', reservations_count: @reservations_counts[[month + 9.hours, language.id]], lessons_count: @lessons_counts[[month + 9.hours, language.id]]

app/views/admins/reservations/by_teacher_and_date.html.haml
%h2
  講師別予約率
= render 'links'
%table.table
  %thead
    %tr
      %th 日付
      - @teachers.each do |teacher|
        %th
          = link_to teacher.username, teacher_path(teacher.id)
  %tbody
    - (@start_date..@end_date).each do |date|
      %tr
        %th
          = date.to_s(:date_jp_weekday)
        - @teachers.each do |teacher|
          = render 'td_reserved_rate', reservations_count: @reservations_counts[[date, teacher.id]], lessons_count: @lessons_counts[[date, teacher.id]]

app/views/admins/reservations/by_teacher_and_month.html.haml
%h2
  講師別予約率
= render 'links'
%table.table
  %thead
    %tr
      %th 日付
      - @teachers.each do |teacher|
        %th
          = link_to teacher.username, teacher_path(teacher.id)
  %tbody
    - month_enum(*Lesson.date_range).each do |month|
      %tr
        %th
          = link_to month.to_s(:month_jp), by_teacher_admins_reservations_path(create_daily_query_params(month))
        - @teachers.each do |teacher|
          = render 'td_reserved_rate', reservations_count: @reservations_counts[[month + 9.hours, teacher.id]], lessons_count: @lessons_counts[[month + 9.hours, teacher.id]]

app/views/admins/reservations/index.html.haml
%h2
  時間別予約率
= render 'links'
= simple_form_for :query, url: admins_reservations_path, method: :get do |f|
  = f.input :start_date, as: :date, label: '開始', html5: true, input_html: { value: @start_date }
  = f.input :end_date, as: :date, label: '終了', html5: true, input_html: { value: @end_date }
  = f.button :submit, '検索', class: 'btn-primary'
%table.table
  %thead
    %tr
      %th 日付
      - (7..22).each do |hour|
        %th
          = hour
  %tbody
    - (@start_date..@end_date).each do |date|
      %tr
        %th
          = date.to_s(:datetime_jp)
        - (7..22).each do |hour|
          = render 'td_reserved_rate', reservations_count: @reservations_counts[[date, hour]], lessons_count: @lessons_counts[[date, hour]]