config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  devise_for :teachers, controllers: {
    registrations: 'teachers/registrations',
    confirmations: 'teachers/confirmations'
  }
  devise_for :students, controllers: {
    registrations: 'students/registrations',
  }
  mount StripeEvent::Engine, at: '/stripe/webhook'
  root to: 'home#index'
  namespace :students do
    resources :lessons, only: [:index] do
      resource :reservation, only: [:create], module: :lessons
      resource :feedback, only: [:show], module: :lessons
    end
    resources :reservations, only: [:index]
    resources :payments, only: [:new, :create] do
      collection do
        get :success
        get :cancel
      end
    end
  end
  namespace :admins do
    resources :teachers, only: [:index, :destroy] do
      member do
        post :become
      end
    end
    resources :reservations, only: [:index] do
      collection do
        get :by_teacher
        get :by_language
      end
    end
  end
  namespace :teachers do
    resources :lessons, only: [:index, :new, :create] do
      collection do
        get :bulk_search
        get :bulk_new
        post :bulk_create
        post :recreate_zoom_user
      end
      resource :feedback, only: [:new, :edit, :create], module: :lessons
      resource :report, only: [:new, :edit, :create], module: :lessons
    end
    resources :students, only: [:show]
  end
  resources :teachers, only: [:show]
  Rails.env.development? && mount(LetterOpenerWeb::Engine, at: '/letter_opener')
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/views/home/index.html.haml
%p
  - if student_signed_in?
    = button_to 'ログアウト', destroy_student_session_path, method: :delete, class: 'btn btn-secondary'
    = link_to 'チケットの確認、購入', new_students_payment_path
    = link_to 'レッスン一覧、予約', students_lessons_path
  - else
    = link_to 'ログイン', new_student_session_path
    = link_to 'サインアップ', new_student_registration_path
%p
  - if teacher_signed_in?
    = button_to '講師ログアウト', destroy_teacher_session_path, method: :delete, class: 'btn btn-secondary'
    = link_to 'レッスン管理', teachers_lessons_path
    = link_to 'プロフィール編集', edit_teacher_registration_path
  - else
    = link_to '講師ログイン', new_teacher_session_path
%p
  - if admin_signed_in?
    = button_to '管理者ログアウト', destroy_admin_session_path, method: :delete, class: 'btn btn-secondary'
    = link_to '講師管理', admins_teachers_path
    = link_to '予約率分析', admins_reservations_path
  - else
    = link_to '管理者ログイン', new_admin_session_path